### PR TITLE
bugfix: fix a typo in chash.reinit

### PR DESCRIPTION
**Pull request by ArchangelSDY**
`newnodes` should be assigned to `self.nodes` rather than `self.newnodes`.

### CODE REVIEW

**Comment by agentzh** [comment]
@doujiang24 Will you have a look at this? Thanks.

**Review by doujiang24 — APPROVED** [review]
@ArchangelSDY nice catch, will you please add a test case for it?

**Comment by ArchangelSDY** [comment]
@doujiang24  Sure, updated.

**Comment by doujiang24** [comment]
@ArchangelSDY Thanks a lot :)

**Comment by ArchangelSDY** [comment]
@doujiang24 Could you merge this PR and tag a new release so that we can pick this change in downstream projects?

**Comment by doujiang24** [comment]
@ArchangelSDY 
merged & added a new release tag: `v0.02rc5`, thanks for your PR :)

**Comment by ElvinEfendi** [comment]
What's the impact of this bug? As long as a user you aren't relying on nodes to be in sync (covered at https://github.com/openresty/lua-resty-balancer/pull/25/files#diff-cad7d8fbdf9d2fb89f5ee95f0b73dff7R338), there should not be any issue, right?

**Comment by ArchangelSDY** [comment]
That's right as long as you don't need to read `self.nodes`. I've added a comment in https://github.com/kubernetes/ingress-nginx/pull/3809#issuecomment-467036731 .

**Pull request merged**
