### PR TITLE
feat: add nginx swrr support

### PR DESCRIPTION
**Pull request by jizhuozhi**

### CODE REVIEW

**Comment by jizhuozhi** [comment]
Hello, @doujiang24 . According to #44 , I create a new PR with nginx swrr implementation, PLAT.

**Comment by zhuizhuhaomeng** [comment]
merged with small modifications.
```
diff --git a/lib/resty/swrr.lua b/lib/resty/swrr.lua
index 591b6a6..7f281c1 100644
--- a/lib/resty/swrr.lua
+++ b/lib/resty/swrr.lua
@@ -125,7 +125,7 @@ local function find(self)
         total = total + weight
         current_weight = current_weight + weight
         current_weights[id] = current_weight
-        
+
         if best_id == nil or best_current_weight < current_weight then
             best_id = id
             best_current_weight = current_weight
```

**Comment by zhuizhuhaomeng** [comment]
@jizhuozhi 

Thank you for your contribution.
After I merged this PR, I found we need to add some description to the doc.
Would please add the doc about the swrr?

https://github.com/openresty/lua-resty-balancer/blob/master/README.markdown#name

**Comment by jizhuozhi** [comment]
> Would please add the doc about the swrr?

Of course, I will do it latter

**Pull request closed without merging**
